# Generated by Django 3.2.18 on 2023-02-26 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=80)),
                ('drink_description', models.CharField(max_length=1000)),
                ('drink_type', models.IntegerField(choices=[(0, 'Wine'), (1, 'Classic Cocktail'), (2, 'Special Cocktail'), (3, 'Aperitif'), (4, 'Digestif'), (5, 'Sparkling Wine'), (6, 'Beer')])),
                ('allergens', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['drink_type', 'drink_name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=100)),
                ('meal_description', models.CharField(max_length=1000)),
                ('meal_type', models.IntegerField(choices=[(0, 'Appetizer'), (1, 'Salad'), (2, 'Main Course'), (3, 'Side Dish'), (4, 'Dessert')])),
                ('allergens', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['meal_type', 'meal_name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_guests', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed')], default=0)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
