# Generated by Django 3.2.18 on 2023-03-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20230315_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='booking_date',
        ),
    ]
